services:
  web:
    build:
      context: ./server
    ports:
      - "3344:3344"
    volumes:
      - ./server/public:/app/public
    environment:
      - PORT=3344
    #restart: unless-stopped
