[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4"
actix-files = "0.6"
env_logger = "0.10"
log = "0.4"
maud = { version = "0.27", features = ["actix-web"] }
serde = { version = "1.0", features = ["derive"] }
mime = "0.3"
